sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3"
install: pip install -e .
script: py.test jellyfish/test.py
after_success:
    - coveralls
notifications:
    email:
        - dev@jamesturk.net
