environment:
    global:
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.run_with_env.cmd"

    matrix:
        - PYTHON: "C:\\Python34"
          PYTHON_VERSION: "3.4.3"
          PYTHON_ARCH: "32"
        - PYTHON: "C:\\Python34-x64"
          PYTHON_VERSION: "3.4.3"
          PYTHON_ARCH: "64"

install:
    - "git submodule update --init --recursive"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "python --version"
    - "%CMD_IN_ENV% pip install -e ."
    - "%CMD_IN_ENV% pip install pytest wheel"

build: false

test_script:
    - "%CMD_IN_ENV% py.test -v jellyfish/test.py"

after_test:
    - "%CMD_IN_ENV% python setup.py bdist_wheel"

artifacts:
    - path: dist\*
